const ALERT="ALERT"
const REFETCH_DATA="REFETCH_DATA"
const ATTACHMENT_MESSAGE="ATTACHMENT FOR MESSAGES"
const NEW_MESSAGE_ALERT="NEW MESSAGE ALERT"
const NEW_REQUEST="NEW_REQUEST"
const NEW_MESSAGE="NEW_MESSAGE"
const HASSAN_TOKEN="HassanCook"
const START_TYPING="START_TYPING"
const STOP_TYPING="STOP_TYPING"
const CHAT_JOIN="CHAT_JOIN"
const CHAT_EXIT="CHAT_EXIT"

export {ALERT,REFETCH_DATA,CHAT_EXIT,CHAT_JOIN,ATTACHMENT_MESSAGE,NEW_MESSAGE_ALERT,NEW_REQUEST,NEW_MESSAGE,HASSAN_TOKEN,START_TYPING,STOP_TYPING}